/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package documentosview;

import java.awt.Dimension;
import static java.lang.Thread.sleep;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Pituba
 */
public class frmCarregando extends javax.swing.JInternalFrame {

    //frmCarregando frmcarregando;
    frmScanner frmscanner;
    
    public frmCarregando() {
               
        //try {
            //UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        //} catch (ClassNotFoundException ex) {
            //Logger.getLogger(frmCarregando.class.getName()).log(Level.SEVERE, null, ex);
        //} catch (InstantiationException ex) {
            //Logger.getLogger(frmCarregando.class.getName()).log(Level.SEVERE, null, ex);
        //} catch (IllegalAccessException ex) {
            //Logger.getLogger(frmCarregando.class.getName()).log(Level.SEVERE, null, ex);
        //} catch (UnsupportedLookAndFeelException ex) {
            //Logger.getLogger(frmCarregando.class.getName()).log(Level.SEVERE, null, ex);
        //}
        initComponents();
        
    }
    
    public void encheprogbar(){
     
        Thread thread = new Thread(){
               @Override
               public void run(){
                   //try {
                       
                       
                            try {
                                frmscanner.salvar();                      
                   } catch (ParseException ex) {
                       Logger.getLogger(frmCarregando.class.getName()).log(Level.SEVERE, null, ex);
                   }

                 }
             
               };
        
        thread.start();
    
    }
        
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgbCarregando = new javax.swing.JProgressBar();
        lblCarregando = new javax.swing.JLabel();

        setFrameIcon(null);

        pgbCarregando.setForeground(new java.awt.Color(51, 255, 0));
        pgbCarregando.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pgbCarregando.setIndeterminate(true);

        lblCarregando.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCarregando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarregando.setText("Aguarde, processando dados...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(pgbCarregando, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCarregando, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblCarregando, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgbCarregando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void setPosicao(){
    
         Dimension dimensao = this.getDesktopPane().getSize();
         this.setLocation((dimensao.width - this.getSize().width)/2,
                         (dimensao.height - this.getSize().height)/2);
               this.toFront();
               
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCarregando;
    private javax.swing.JProgressBar pgbCarregando;
    // End of variables declaration//GEN-END:variables
}
